yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница сообщества (группы) пользователей со списком постов
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание новой записи
    path('create/', views.post_create, name='post_create'),
    # Редактирование одной из своих записей
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    # сначала шаблоны в приложении posts
    path('', include('posts.urls', namespace='posts')),
    # Админка Django (встроенная)
    path('admin/', admin.site.urls),
    # Кастомные страницы аутентификации
    # префикс 'auth/' обозначает название приложения
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # тогда Джанго будет искать их в модуле django.contrib.auth,
    # так как они идут ПОСЛЕ users.urls
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Класс описывает таблицу сообществ (по группам авторов)."""
    # Название сообщества
    title = models.CharField(max_length=200)
    # название для адресной строки браузера
    slug = models.SlugField(unique=True)
    # Описание сообщества
    description = models.TextField()

    def __str__(self) -> str:
        # метод для вывода title при печати объекта
        return self.title


class Post(models.Model):
    """ Класс описывает таблицу для хранения постов."""
    # Текст поста
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    # Дата опубликования (можно использовать в фильтрах)
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    # поле "автор" - для связи с таблицей User
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='автор'
    )
    # Поле для связи с таблицей Group
    group = models.ForeignKey(
        Group,
        related_name='posts',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        # метод для вывода текста при печати объекта
        return self.text[:15]


class Comment(models.Model):
    """ Класс описывает таблицу для хранения комментариев к постам."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='автор'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Оставьте комментарий'
    )
    # Время создания (можно использовать в фильтрах)
    created = models.DateTimeField(
        'Время публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    """ Модель описывает таблицу для связи пользоветелей-подписчиков
        и их подписок.
    """
    # Тот, на которого подписались
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка'
    )
    # Подписчик
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {'text': 'Текст поста', 'group': 'Группа'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'text'}

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import (Group, Post, User, Follow)


def get_page_from_paginator(list_items, request):
    """ Функция для вызова паджинатора.
        Возвращает объект page_obg с разбитыми постранично элементами.
        """
    page_number = request.GET.get('page')
    p = Paginator(list_items, settings.PAGINATION_COUNT)
    page_obj = p.get_page(page_number)
    return page_obj


@cache_page(20, cache='default', key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    context = {
        'page_obj': get_page_from_paginator(post_list, request)
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_page_from_paginator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author_profile = get_object_or_404(User, username=username)
    author_posts = author_profile.posts.all()
    page_obj = get_page_from_paginator(author_posts, request)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author_profile
    ).exists()
    context = {
        'author': author_profile,
        'following': following,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    current_post = get_object_or_404(Post, id=post_id)
    comments = current_post.comments.all()
    context = {
        'current_post': current_post,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """ Добавляет новую запись."""
    is_edit = False
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user.username)
    # если запрос не POST, a GET или форма невалидна - создаем пустую форму
    context = {'form': form, 'is_edit': is_edit}
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    """ Редактирует существующую запись."""
    current_post = get_object_or_404(Post, pk=post_id)
    if request.user.pk != current_post.author_id:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=current_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    # В случае если форма невалидна (или запрос GET)
    # создается форма с данными для редактирования
    context = {
        'form': form, 'post': current_post, 'is_edit': True}
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    """ Добавляет комментарий к посту."""
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, id=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """ Представляет страницу со списком постов всех авторов,
        на которых подписан текущий пользователь"""
    followed_posts = (
        Post.objects.filter(
            author__following__user=request.user
        )
    )
    page_obj = get_page_from_paginator(followed_posts, request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """ Функция реализует возможность подписаться на автора."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        # Если подписка уже есть, или пользователь рассматривает свою страницу
        # тогда запрос на подписку будет проигнорирован
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """ Функция реализует возможность отписаться от автора."""
    author = get_object_or_404(User, username=username)
    get_object_or_404(Follow, user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}  
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <h1 style="text-align:center">
    Последние обновления на сайте
  </h1>
  {% for post in page_obj.object_list %}
    {% include 'posts/includes/current_post.html' %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}         
  {% include 'posts/includes/paginator.html' %}
  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{ group.title|default:"Лев Толстой – зеркало русской революции" }}
{% endblock %}
{% block content %}
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'posts/includes/current_post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}  
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}  
  <h1 style="text-align:center">
    Последние обновления на сайте
  </h1>
  {% for post in page_obj.object_list %}
    {% include 'posts/includes/current_post.html' %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}         
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}  
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись  
            {% endif %}         
          </div>
          <div class="card-body"> 
            {% load user_filters %} {# Загружаем фильтры #}
            {% if form.errors %}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post.id %}"
              {% else %}
                action="{% url 'posts:post_create' %}"
              {% endif %}>
              {% csrf_token %}   
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}                  
                    {% if field.field.required %}
                    <span class="required text-danger" >*</span>   
                    {% endif %}               
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>  
                  {% endif %}                
                </div>
              {% endfor %}            
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}  
    {{ current_post.text|truncatechars:30 }} 
{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ current_post.pub_date }} 
                </li>
                {% if current_post.group %}   
                    <li class="list-group-item">
                        Группа: {{ current_post.group.title }}
                        <a href="{% url 'posts:group_list' current_post.group.slug %}">все записи группы</a>
                    </li>
                {% endif %}        
                <li class="list-group-item">
                    Автор: {{ current_post.author }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span >{{ current_post.author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' current_post.author.username %}">
                        все посты пользователя 
                    </a>
                </li>
                <li class="list-group-item">
                    {% if current_post.author == request.user %}
                        <a href="{% url 'posts:post_edit' current_post.id %}">Редактировать </a>
                    {% endif %}
                </li>
            </ul>
            
        </aside>
     
        <article class="col-12 col-md-8">
          {% thumbnail current_post.image "900x550" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}   
          <p>
              {{ current_post.text|linebreaks }}
          </p>
          {% if request.user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' current_post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                  <div>{{ comment.created|date:"d M Y, h.m.s" }}</div>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %} 
        </article>
    </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}  
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ posts_count }}</h3>
      {% if request.user != author and request.user.is_authenticated %}
      <!-- Такой переключатель не будет показан самому автору и неавторизованному пользователю-->
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}  
      </div>
    {% for post in page_obj.object_list %}
      {% include 'posts/includes/current_post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}       
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}